<!-- CORE PLUGINS-->
<script src="{{asset('')}}dash/assets/vendors/jquery/dist/jquery.min.js" type="text/javascript"></script>
<script src="{{asset('')}}dash/assets/vendors/popper.js/dist/umd/popper.min.js" type="text/javascript"></script>
<script src="{{asset('')}}dash/assets/vendors/bootstrap/dist/js/bootstrap.min.js" type="text/javascript"></script>
<script src="{{asset('')}}dash/assets/vendors/metisMenu/dist/metisMenu.min.js" type="text/javascript"></script>
<script src="{{asset('')}}dash/assets/vendors/jquery-slimscroll/jquery.slimscroll.min.js" type="text/javascript"></script>
<script src="{{asset('')}}dash/assets/vendors/chart.js/dist/Chart.min.js" type="text/javascript"></script>
<script src="{{asset('')}}dash/assets/vendors/jvectormap/jquery-jvectormap-2.0.3.min.js" type="text/javascript"></script>
<script src="{{asset('')}}dash/assets/vendors/jvectormap/jquery-jvectormap-world-mill-en.js" type="text/javascript"></script>
<script src="{{asset('')}}dash/assets/vendors/jvectormap/jquery-jvectormap-us-aea-en.js" type="text/javascript"></script>
<script src="{{asset('')}}dash/assets/js/app.min.js" type="text/javascript"></script>
<script src="{{asset('/')}}dash/plugins/fileinput.min.js" type="text/javascript"></script>
<script src="{{asset('')}}dash/assets/vendors/DataTables/datatables.min.js" type="text/javascript"></script>
<script src="{{asset('')}}dash/assets/vendors/summernote/dist/summernote.min.js" type="text/javascript"></script>
<script src="{{asset('')}}dash/assets/vendors/bootstrap-markdown/js/bootstrap-markdown.js" type="text/javascript"></script>
<script src="{{ asset('dash/plugins/pnotify/pnotify.min.js')}}"></script>
